### ISSUE TITLE
Port to Python 3.x

### ISSUE THREAD

**Issue by xyproto** [xyproto/monkeyjump#1]
Python 2 will reach its end-of-life soon.

This is a feature request to port Monkeyjump from Python 2 to Python 3.

**Comment by dmoneyballer** [comment]
I'll work on this. I've forked and have made some modifications. now I'll test them

**Comment by xyproto** [comment]
Great. :slightly_smiling_face:

**Comment by dmoneyballer** [comment]
What does running gnugo --mode gtp do? I can't figure out why it's raising this error.

![image](https://user-images.githubusercontent.com/36215373/66521193-ea214e00-eaa7-11e9-858f-8dc600de9fc8.png)

**Comment by xyproto** [comment]
It runs the gnugo executable, that is expected to be in the path. It is the "AI" program that can play Go. One of many a available Go engines.

I assume that gnugo isn't installed?

**Comment by dmoneyballer** [comment]
I installed it and it started working. I've got it up and It's not erroring out but is stuck on the loading screen. I added lots of print statements to make sure it was running properly through image engine.py but I've never used pygame before and I don't really know how to proceed from here.
![Screenshot from 2019-10-09 17-50-43](https://user-images.githubusercontent.com/36215373/66528556-8ace3880-eabd-11e9-92df-ead4fee8e79e.png)

**Comment by xyproto** [comment]
I think a call to the `.communicate()` method is missing, which makes the program stop at `status = self.from_gnugo.read(1)`. Not quite sure how to best fix it in Python 3, though. Python 3 has different quirks than Python 2 when it comes to communicating with processes using stdout and stdin.

**Comment by xyproto** [comment]
Right now, I would rather rewrite Monkeyjump in a completely different language than port it to Python 3, since it appeared to be more trouble than expected.
